/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_list = 1,
  anon_sym_LT = 2,
  anon_sym_GT = 3,
  anon_sym_oneof = 4,
  anon_sym_record = 5,
  anon_sym_COMMA = 6,
  anon_sym_COLON = 7,
  aux_sym_field_name_token1 = 8,
  aux_sym_field_name_token2 = 9,
  anon_sym_bool = 10,
  anon_sym_path = 11,
  anon_sym_string = 12,
  anon_sym_int = 13,
  anon_sym_nothing = 14,
  anon_sym_float = 15,
  anon_sym_binary = 16,
  anon_sym_duration = 17,
  anon_sym_datetime = 18,
  sym_source_file = 19,
  sym_type = 20,
  sym_composed_type = 21,
  sym_list_type = 22,
  sym_oneof_type = 23,
  sym_record_type = 24,
  sym_field_defn = 25,
  sym_field_name = 26,
  sym_value_type = 27,
  aux_sym_record_type_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_list] = "list",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_oneof] = "oneof",
  [anon_sym_record] = "record",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [aux_sym_field_name_token1] = "field_name_token1",
  [aux_sym_field_name_token2] = "field_name_token2",
  [anon_sym_bool] = "bool",
  [anon_sym_path] = "path",
  [anon_sym_string] = "string",
  [anon_sym_int] = "int",
  [anon_sym_nothing] = "nothing",
  [anon_sym_float] = "float",
  [anon_sym_binary] = "binary",
  [anon_sym_duration] = "duration",
  [anon_sym_datetime] = "datetime",
  [sym_source_file] = "source_file",
  [sym_type] = "type",
  [sym_composed_type] = "composed_type",
  [sym_list_type] = "list_type",
  [sym_oneof_type] = "oneof_type",
  [sym_record_type] = "record_type",
  [sym_field_defn] = "field_defn",
  [sym_field_name] = "field_name",
  [sym_value_type] = "value_type",
  [aux_sym_record_type_repeat1] = "record_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_list] = anon_sym_list,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_oneof] = anon_sym_oneof,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_field_name_token1] = aux_sym_field_name_token1,
  [aux_sym_field_name_token2] = aux_sym_field_name_token2,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_path] = anon_sym_path,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_nothing] = anon_sym_nothing,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_binary] = anon_sym_binary,
  [anon_sym_duration] = anon_sym_duration,
  [anon_sym_datetime] = anon_sym_datetime,
  [sym_source_file] = sym_source_file,
  [sym_type] = sym_type,
  [sym_composed_type] = sym_composed_type,
  [sym_list_type] = sym_list_type,
  [sym_oneof_type] = sym_oneof_type,
  [sym_record_type] = sym_record_type,
  [sym_field_defn] = sym_field_defn,
  [sym_field_name] = sym_field_name,
  [sym_value_type] = sym_value_type,
  [aux_sym_record_type_repeat1] = aux_sym_record_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_list] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_oneof] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_field_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_name_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_path] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nothing] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_binary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_duration] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_datetime] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_composed_type] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_oneof_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_field_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_value_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_record_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(56);
      ADVANCE_MAP(
        '"', 55,
        ',', 62,
        ':', 63,
        '<', 58,
        '>', 59,
        'b', 21,
        'd', 3,
        'f', 26,
        'i', 33,
        'l', 19,
        'n', 36,
        'o', 31,
        'p', 5,
        'r', 10,
        's', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(52);
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(60);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(68);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(70);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(67);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(30);
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(66);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 54:
      if (lookahead == 'y') ADVANCE(72);
      END_STATE();
    case 55:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_list);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_oneof);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_field_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_field_name_token2);
      if (lookahead == '"') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_path);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_nothing);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_binary);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_duration);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_datetime);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_list] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_oneof] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_field_name_token2] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_path] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_nothing] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_binary] = ACTIONS(1),
    [anon_sym_duration] = ACTIONS(1),
    [anon_sym_datetime] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym_type] = STATE(23),
    [sym_composed_type] = STATE(6),
    [sym_list_type] = STATE(7),
    [sym_oneof_type] = STATE(7),
    [sym_record_type] = STATE(7),
    [sym_value_type] = STATE(6),
    [anon_sym_list] = ACTIONS(3),
    [anon_sym_oneof] = ACTIONS(5),
    [anon_sym_record] = ACTIONS(7),
    [anon_sym_bool] = ACTIONS(9),
    [anon_sym_path] = ACTIONS(9),
    [anon_sym_string] = ACTIONS(9),
    [anon_sym_int] = ACTIONS(9),
    [anon_sym_nothing] = ACTIONS(9),
    [anon_sym_float] = ACTIONS(9),
    [anon_sym_binary] = ACTIONS(9),
    [anon_sym_duration] = ACTIONS(9),
    [anon_sym_datetime] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_type] = STATE(4),
    [sym_composed_type] = STATE(6),
    [sym_list_type] = STATE(7),
    [sym_oneof_type] = STATE(7),
    [sym_record_type] = STATE(7),
    [sym_value_type] = STATE(6),
    [anon_sym_list] = ACTIONS(3),
    [anon_sym_oneof] = ACTIONS(5),
    [anon_sym_record] = ACTIONS(7),
    [anon_sym_bool] = ACTIONS(9),
    [anon_sym_path] = ACTIONS(9),
    [anon_sym_string] = ACTIONS(9),
    [anon_sym_int] = ACTIONS(9),
    [anon_sym_nothing] = ACTIONS(9),
    [anon_sym_float] = ACTIONS(9),
    [anon_sym_binary] = ACTIONS(9),
    [anon_sym_duration] = ACTIONS(9),
    [anon_sym_datetime] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_type] = STATE(25),
    [sym_composed_type] = STATE(6),
    [sym_list_type] = STATE(7),
    [sym_oneof_type] = STATE(7),
    [sym_record_type] = STATE(7),
    [sym_value_type] = STATE(6),
    [anon_sym_list] = ACTIONS(3),
    [anon_sym_oneof] = ACTIONS(5),
    [anon_sym_record] = ACTIONS(7),
    [anon_sym_bool] = ACTIONS(9),
    [anon_sym_path] = ACTIONS(9),
    [anon_sym_string] = ACTIONS(9),
    [anon_sym_int] = ACTIONS(9),
    [anon_sym_nothing] = ACTIONS(9),
    [anon_sym_float] = ACTIONS(9),
    [anon_sym_binary] = ACTIONS(9),
    [anon_sym_duration] = ACTIONS(9),
    [anon_sym_datetime] = ACTIONS(9),
  },
  [STATE(4)] = {
    [sym_type] = STATE(28),
    [sym_composed_type] = STATE(6),
    [sym_list_type] = STATE(7),
    [sym_oneof_type] = STATE(7),
    [sym_record_type] = STATE(7),
    [sym_value_type] = STATE(6),
    [anon_sym_list] = ACTIONS(3),
    [anon_sym_oneof] = ACTIONS(5),
    [anon_sym_record] = ACTIONS(7),
    [anon_sym_bool] = ACTIONS(9),
    [anon_sym_path] = ACTIONS(9),
    [anon_sym_string] = ACTIONS(9),
    [anon_sym_int] = ACTIONS(9),
    [anon_sym_nothing] = ACTIONS(9),
    [anon_sym_float] = ACTIONS(9),
    [anon_sym_binary] = ACTIONS(9),
    [anon_sym_duration] = ACTIONS(9),
    [anon_sym_datetime] = ACTIONS(9),
  },
  [STATE(5)] = {
    [sym_type] = STATE(19),
    [sym_composed_type] = STATE(6),
    [sym_list_type] = STATE(7),
    [sym_oneof_type] = STATE(7),
    [sym_record_type] = STATE(7),
    [sym_value_type] = STATE(6),
    [anon_sym_list] = ACTIONS(3),
    [anon_sym_oneof] = ACTIONS(5),
    [anon_sym_record] = ACTIONS(7),
    [anon_sym_bool] = ACTIONS(9),
    [anon_sym_path] = ACTIONS(9),
    [anon_sym_string] = ACTIONS(9),
    [anon_sym_int] = ACTIONS(9),
    [anon_sym_nothing] = ACTIONS(9),
    [anon_sym_float] = ACTIONS(9),
    [anon_sym_binary] = ACTIONS(9),
    [anon_sym_duration] = ACTIONS(9),
    [anon_sym_datetime] = ACTIONS(9),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_list] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(11),
    [anon_sym_oneof] = ACTIONS(11),
    [anon_sym_record] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(11),
    [anon_sym_bool] = ACTIONS(11),
    [anon_sym_path] = ACTIONS(11),
    [anon_sym_string] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(11),
    [anon_sym_nothing] = ACTIONS(11),
    [anon_sym_float] = ACTIONS(11),
    [anon_sym_binary] = ACTIONS(11),
    [anon_sym_duration] = ACTIONS(11),
    [anon_sym_datetime] = ACTIONS(11),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_list] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_oneof] = ACTIONS(13),
    [anon_sym_record] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [anon_sym_path] = ACTIONS(13),
    [anon_sym_string] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(13),
    [anon_sym_nothing] = ACTIONS(13),
    [anon_sym_float] = ACTIONS(13),
    [anon_sym_binary] = ACTIONS(13),
    [anon_sym_duration] = ACTIONS(13),
    [anon_sym_datetime] = ACTIONS(13),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_list] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_oneof] = ACTIONS(15),
    [anon_sym_record] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_path] = ACTIONS(15),
    [anon_sym_string] = ACTIONS(15),
    [anon_sym_int] = ACTIONS(15),
    [anon_sym_nothing] = ACTIONS(15),
    [anon_sym_float] = ACTIONS(15),
    [anon_sym_binary] = ACTIONS(15),
    [anon_sym_duration] = ACTIONS(15),
    [anon_sym_datetime] = ACTIONS(15),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_list] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_oneof] = ACTIONS(17),
    [anon_sym_record] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(17),
    [anon_sym_bool] = ACTIONS(17),
    [anon_sym_path] = ACTIONS(17),
    [anon_sym_string] = ACTIONS(17),
    [anon_sym_int] = ACTIONS(17),
    [anon_sym_nothing] = ACTIONS(17),
    [anon_sym_float] = ACTIONS(17),
    [anon_sym_binary] = ACTIONS(17),
    [anon_sym_duration] = ACTIONS(17),
    [anon_sym_datetime] = ACTIONS(17),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_list] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_oneof] = ACTIONS(19),
    [anon_sym_record] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_bool] = ACTIONS(19),
    [anon_sym_path] = ACTIONS(19),
    [anon_sym_string] = ACTIONS(19),
    [anon_sym_int] = ACTIONS(19),
    [anon_sym_nothing] = ACTIONS(19),
    [anon_sym_float] = ACTIONS(19),
    [anon_sym_binary] = ACTIONS(19),
    [anon_sym_duration] = ACTIONS(19),
    [anon_sym_datetime] = ACTIONS(19),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_list] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_oneof] = ACTIONS(21),
    [anon_sym_record] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_bool] = ACTIONS(21),
    [anon_sym_path] = ACTIONS(21),
    [anon_sym_string] = ACTIONS(21),
    [anon_sym_int] = ACTIONS(21),
    [anon_sym_nothing] = ACTIONS(21),
    [anon_sym_float] = ACTIONS(21),
    [anon_sym_binary] = ACTIONS(21),
    [anon_sym_duration] = ACTIONS(21),
    [anon_sym_datetime] = ACTIONS(21),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_list] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_oneof] = ACTIONS(23),
    [anon_sym_record] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_bool] = ACTIONS(23),
    [anon_sym_path] = ACTIONS(23),
    [anon_sym_string] = ACTIONS(23),
    [anon_sym_int] = ACTIONS(23),
    [anon_sym_nothing] = ACTIONS(23),
    [anon_sym_float] = ACTIONS(23),
    [anon_sym_binary] = ACTIONS(23),
    [anon_sym_duration] = ACTIONS(23),
    [anon_sym_datetime] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    STATE(15), 1,
      sym_field_defn,
    STATE(26), 1,
      sym_field_name,
    ACTIONS(25), 2,
      aux_sym_field_name_token1,
      aux_sym_field_name_token2,
  [11] = 3,
    STATE(18), 1,
      sym_field_defn,
    STATE(26), 1,
      sym_field_name,
    ACTIONS(25), 2,
      aux_sym_field_name_token1,
      aux_sym_field_name_token2,
  [22] = 3,
    ACTIONS(27), 1,
      anon_sym_GT,
    ACTIONS(29), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_record_type_repeat1,
  [32] = 3,
    ACTIONS(29), 1,
      anon_sym_COMMA,
    ACTIONS(31), 1,
      anon_sym_GT,
    STATE(17), 1,
      aux_sym_record_type_repeat1,
  [42] = 3,
    ACTIONS(33), 1,
      anon_sym_GT,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_record_type_repeat1,
  [52] = 1,
    ACTIONS(33), 2,
      anon_sym_GT,
      anon_sym_COMMA,
  [57] = 1,
    ACTIONS(38), 2,
      anon_sym_GT,
      anon_sym_COMMA,
  [62] = 1,
    ACTIONS(40), 1,
      anon_sym_LT,
  [66] = 1,
    ACTIONS(42), 1,
      anon_sym_LT,
  [70] = 1,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
  [74] = 1,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
  [78] = 1,
    ACTIONS(48), 1,
      anon_sym_LT,
  [82] = 1,
    ACTIONS(50), 1,
      anon_sym_GT,
  [86] = 1,
    ACTIONS(52), 1,
      anon_sym_COLON,
  [90] = 1,
    ACTIONS(54), 1,
      anon_sym_COLON,
  [94] = 1,
    ACTIONS(56), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 11,
  [SMALL_STATE(15)] = 22,
  [SMALL_STATE(16)] = 32,
  [SMALL_STATE(17)] = 42,
  [SMALL_STATE(18)] = 52,
  [SMALL_STATE(19)] = 57,
  [SMALL_STATE(20)] = 62,
  [SMALL_STATE(21)] = 66,
  [SMALL_STATE(22)] = 70,
  [SMALL_STATE(23)] = 74,
  [SMALL_STATE(24)] = 78,
  [SMALL_STATE(25)] = 82,
  [SMALL_STATE(26)] = 86,
  [SMALL_STATE(27)] = 90,
  [SMALL_STATE(28)] = 94,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composed_type, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_type, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_oneof_type, 5, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 4, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 5, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_defn, 3, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [44] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sample_grammar(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sample_grammar",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
